# ============================================================
# Preprocess Config for SRJ (Standardize + Flatten)
# ============================================================

data:
  train_graphs:
    - "/share/lustre/yzhu/dijet_slice/part0_0.25percent/graphs_dijet_batch0_ln_kT_cut_None_with_pt"
    - "/share/lustre/yzhu/dijet_slice/part0_0.25percent/graphs_dijet_batch1_ln_kT_cut_None_with_pt"
  test_graphs:
    - "/share/lustre/yzhu/dijet_slice/part1_0.25percent/graphs_dijet_batch0_ln_kT_cut_None_with_pt"
    - "/share/lustre/yzhu/dijet_slice/part1_0.25percent/graphs_dijet_batch1_ln_kT_cut_None_with_pt"

  out_dir: "/share/lustre/yzhu/dijet_slice/preprocessed"

  # mean/std JSON
  meanstd_json: "/share/lustre/yzhu/dijet_slice/part0_0.25percent/meanstd_part0.json"


# ============================================================
# Jet selection
# ============================================================
cut_pt_eta_mass: True
config_signal_path: "./configs/config_signal_SRJ.yaml"
signal: srj


# ============================================================
# Flattening options (train only)
# ============================================================
flatten_pt: True
flatten_eta: True
n_bins_pt: 100
n_bins_eta: 50


# ============================================================
# Compute resources
# ============================================================
num_workers: 4
