# ============================================================
# Data and output paths
# ============================================================
data:
  paths_to_test_file_root: "/share/lustre/yzhu/dijet_data/data_dijet_part1_0.25percent/data_dijet_part1_0.25percent_ln_kT_cut_None.root"
  paths_to_test_file_graphs: "/share/lustre/yzhu/dijet_data/data_dijet_part1_0.25percent/graphs_dijet_part1_0.25percent_ln_kT_cut_None_with_pt*"
  path_to_outdir: "/share/lustre/yzhu/srjtest/{sample}/"

  output_suffix: "_score_multiModel"
  sample: "TEST_05qcd_1z"
  kT_cut: null


# ============================================================
# Model evaluation settings
# ============================================================
test:

  models_to_run:

    - tag: "LundNet_nominal"        # Distinct Root branch names
      arch: "LundNet"               # Model type
      ckpt: "/path/to/LundNet_nominal.pt"

    - tag: "LundNet_variation"      
      arch: "LundNet"
      ckpt: "/path/to/LundNet_variation.pt"

    - tag: "GINNet_v1"              
      arch: "GINNet"
      ckpt: "/path/to/GINNet_v1.pt"

  # ROOT branch names：generated from TAG
  scores_branch_name: "fjet_{tag}_score"

  batch_size: 2048
