# NOTE: it is assumed all data in a single file has the same DSID
path_to_rootfiles: 
- '/share/lustre/yzhu/dijet/user.yuanda.mc20_13TeV.364702.e7142_s3681_r13144_p6859.parent_ANALYSIS.root/*.root'
- '/share/lustre/yzhu/dijet/user.yuanda.mc20_13TeV.364703.e7142_s3681_r13144_p6859.parent_ANALYSIS.root/*.root'
- '/share/lustre/yzhu/dijet/user.yuanda.mc20_13TeV.364704.e7142_s3681_r13144_p6859.parent_ANALYSIS.root/*.root'
- '/share/lustre/yzhu/dijet/user.yuanda.mc20_13TeV.364705.e7142_s3681_r13144_p6859.parent_ANALYSIS.root/*.root'
- '/share/lustre/yzhu/dijet/user.yuanda.mc20_13TeV.364706.e7142_s3681_r13144_p6859.parent_ANALYSIS.root/*.root'
- '/share/lustre/yzhu/dijet/user.yuanda.mc20_13TeV.364707.e7142_s3681_r13144_p6859.parent_ANALYSIS.root/*.root'  

n_files: null

event_fractions: {0.0025: 2, 0.005: 1, 0.01: 2, 0.02: 1, 0.05: 19}
event_fraction_idx: null
# event_fractions:
#   0.7: 1
#   0.3: 1
# event_fraction_idx: null


out_dir: "/share/lustre/yzhu/dijet_data/data_{id}{frac}"
out_file_name_graphs: "graphs_{id}{frac}_ln_kT_cut_{kT_cut}{include_pt}"
out_file_name_root: "data_{id}{frac}_ln_kT_cut_{kT_cut}.root"

id: "dijet"

# -------------------------------------------------------------------
# Use SRJ signal config
# -------------------------------------------------------------------
signal_config_file: "configs/config_signal_srj.yaml"
signal: srj              # IMPORTANT: for SRJ dataset
signal_name_in_weight: False   # SRJ use no weight branches，or reweight flat-pt

# -------------------------------------------------------------------
# selection and output variables
# -------------------------------------------------------------------
kT_cut: null
include_pt: True
